Split costmaps
bit-bots/bitbots_navigation pull request #137
Opened 2021-06-11 15:20 UTC by Flova

## Proposed changes
*  Adapt global costmap size to field size + margin
* Split the costmap into one for the ball obstacle and one for the robots. 
* Maybe also split the robot obstacles by team in the futureNot

Note this needs a behavior fix before its merge

2021-06-11 15:58 UTC, SammyRamone approved these changes

2021-06-12 14:48 UTC, timonegk approved these changes

2021-06-12 16:17 UTC, timonegk requested changes

2021-06-12 16:17 UTC, timonegk commented on bitbots_move_base/config/costmap_common_config.yaml
>    voxel_decay:              1.0   # seconds if linear, e^n if exponential
```suggestion
  voxel_decay:              0.3   # seconds if linear, e^n if exponential
```

2021-06-12 18:11 UTC, timonegk approved these changes

2021-06-12 18:11 UTC, merged