Added bad option to localization script
bit-bots/bitbots_navigation pull request #71
Opened 2020-11-16 19:56 UTC by NFiedler

## Proposed changes
Now we can publish/simulate an extremely bad localization result.

## Related issues
Needed for tests of https://github.com/bit-bots/bitbots_behavior/pull/97

## Necessary checks
- [x] Update package version
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [x] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

2020-11-16 21:32 UTC, timonegk requested changes

2020-11-16 21:32 UTC, timonegk commented on bitbots_localization/scripts/rviz_localization_sim.py
> +        pose.pose.covariance[5] = 100
```suggestion
        pose.pose.covariance[7] = 100
```

2020-11-17 09:09 UTC, NFiedler commented
Thanks @timonegk

2020-11-17 09:56 UTC, timonegk approved these changes

2020-11-17 09:56 UTC, merged