Working localization handler
bit-bots/bitbots_navigation pull request #92
Opened 2021-02-05 01:45 UTC by Flova

## Proposed changes
* Move localization handler to the right folder
* Add it to the build pipeline and launch file
* Fix multiple bugs in the handler
* Add DSD code to stop the localization during falling->standup

2021-02-05 15:12 UTC, Flova commented on bitbots_localization/src/bitbots_localization/localization_dsd/actions/initialize.py
> +        print(  self.blackboard.poseX,
Remove debug print

2021-02-05 15:35 UTC, jaagut commented on bitbots_localization/src/bitbots_localization/localization_dsd/actions/stop.py
> +        super(AbstractLocalizationPause, self).__init__(blackboard, dsd, parameters=None)
`parameters=None` should be `parameters=parameters`
and below

2021-02-05 15:35 UTC, jaagut commented on bitbots_localization/src/bitbots_localization/localization_dsd/actions/stop.py
> +            print(f"Service call failed: {e}")
use `rospy.logerr` as above

2021-02-05 15:35 UTC, jaagut commented on bitbots_localization/src/bitbots_localization/localization_dsd/actions/initialize.py
> +            print(f"Service call failed: {e}")
Replace all these prints with `rospy.logerr`

2021-02-05 15:35 UTC, jaagut commented on bitbots_localization/src/bitbots_localization/localization_dsd/actions/initialize.py
> +        reset_filter_prox = rospy.ServiceProxy('bitbots_localization/reset_filter', reset_filter)
Please rename all `reset_filter_prox` with `reset_filter_proxy`.

2021-02-05 15:35 UTC, jaagut commented on bitbots_localization/src/bitbots_localization/localization_dsd/actions/initialize.py
> +        print(  self.blackboard.poseX,
?DEBUG?

2021-02-05 15:35 UTC, jaagut commented on bitbots_localization/src/localization.cpp
> +  estimateMsg.pose.pose.orientation.z = q.w();
Classic...

2021-02-05 15:35 UTC, jaagut commented on bitbots_localization/src/bitbots_localization/localization_dsd/decisions/decisions.py
> +class CheckFalling(AbstractDecisionElement):
Maybe merge these Decisions

2021-02-25 18:02 UTC, timonegk requested changes
First set of change requests

2021-02-25 18:25 UTC, timonegk approved these changes
Tested, works fine.

2021-02-25 18:25 UTC, merged